// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv_QQcC4cTi_9iM5zJn7FpevlqcHhJNeo',
    appId: '1:68520199224:ios:bcb7f1cf1a4099369012cd',
    messagingSenderId: '68520199224',
    projectId: 'thinknode-9fc96',
    storageBucket: 'thinknode-9fc96.firebasestorage.app',
    iosBundleId: 'com.app.thinknode',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFT6lu23bBA-lNmeNpOu0lk3DaAARgcaI',
    appId: '1:68520199224:android:ba5ca58645f28fde9012cd',
    messagingSenderId: '68520199224',
    projectId: 'thinknode-9fc96',
    storageBucket: 'thinknode-9fc96.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzhRddKvdZp7vdZhf5SpWa-dNMiw_50bA',
    appId: '1:68520199224:web:633a393af146bb009012cd',
    messagingSenderId: '68520199224',
    projectId: 'thinknode-9fc96',
    authDomain: 'thinknode-9fc96.firebaseapp.com',
    storageBucket: 'thinknode-9fc96.firebasestorage.app',
    measurementId: 'G-C4S2GMXQY7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv_QQcC4cTi_9iM5zJn7FpevlqcHhJNeo',
    appId: '1:68520199224:ios:bcb7f1cf1a4099369012cd',
    messagingSenderId: '68520199224',
    projectId: 'thinknode-9fc96',
    storageBucket: 'thinknode-9fc96.firebasestorage.app',
    iosBundleId: 'com.app.thinknode',
  );

}
